online_store/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('add_in_cat/<int:product_id>', views.cart_add_in_catalog, name='cart_add_in_catalog'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('cart_clear', views.cart_clear, name='cart_clear'),
]

online_store/online_store/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import BaseView
from django.conf import settings
from django.conf.urls.static import static
from shop.api import OrderAPIUpdate

urlpatterns = [
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('catalog/', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/order/<int:pk>/', OrderAPIUpdate.as_view(), name='order'),
    path('api/v1/order/auth/', include('rest_framework.urls')),
    path('', BaseView.as_view(), name='base'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_store/shop/urls.py
from django.urls import path
from django.views.decorators.http import require_POST

from . import views

app_name = 'shop'

urlpatterns = [
    path('<slug:cat_slug>', views.ProductCategory.as_view(), name='category'),
    path('', views.ProductListView.as_view(), name='catalog'),
    path('product/<int:pk>', views.ProductDetailView.as_view(), name='product'),
    path('product/<int:pk>/review', require_POST(views.AddReviews.as_view()), name='review'),
    path('order/create', views.OrderCreateView.as_view(), name='order_create'),
    path('order/payment/<int:pk>/', views.payment, name='order_pay'),
    path('order/progresspay', views.progress_pay, name='progress_pay'),
    path('order/history', views.OrderHistoryView.as_view(), name='order_history'),
    path('order/detail/<int:pk>/', views.OrderDetail.as_view(), name='order_detail'),
]

online_store/cart/models.py
from django.db import models

# Create your models here.

online_store/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    # quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, widget=forms.Select(attrs={'class': 'Amount-input form-input'}))
    quantity = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'Amount-input form-input',
                                                                'name': 'amount',
                                                                'type': 'text',
                                                                'value': '1'}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

online_store/cart/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import CartAddProductForm
from shop.models import Product
from django.urls import reverse_lazy
from django.contrib import messages


def cart_add_in_catalog(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    cart.add(product=product)

    return redirect('shop:catalog')


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])

    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'update': True
            })
    # return render(request, 'cart/cart.html', {'cart': cart})
    return render(request, 'cart/detail.html', {'cart': cart})


def cart_clear(request):
    cart = Cart(request)
    cart.clear()

    return redirect('cart:cart_detail')

online_store/templates/cart/detail.html
{% extends "index.html" %}
{% load static %}
<!--Это тестовый вариант корзины имеющий оформление отличный от предложенного -->
{% block middle %}
    <div class="Middle">
    <div class="Section">
      <div class="wrap">
    <h1>Ваша корзина товаров</h1>
      {% if cart %}
  <table class="cart">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Полная цена</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}" alt="" />
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "cart:cart_add" product.id %}" method="post" class="add">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                {% csrf_token %}
                <input type="submit" value="Обновить">
              </form>
            </td>
            <td><a href="{% url "cart:cart_remove" product.id %}">Удалить</a></td>
            <td class="num">{{ item.price }} руб.</td>
            <td class="num">{{ item.total_price }} руб.</td>
          </tr>
        {% endwith %}
      {% endfor %}
        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price }} руб.</td>
        </tr>
    </tbody>
  </table>

  <p class="text-right">
    <a href="{% url 'shop:catalog' %}" class="btn">Продолжить Шопинг</a>
  </p>
  <div class="buttons"><a class="btn btn_square btn_dark btn_narrow" href="{% url 'cart:cart_clear' %}">Очистить корзину</a></div>

  <!--<div class="Order-footer"><a class="btn btn_primary btn_lg" href="{% url 'shop:catalog' %}">Продолжить Шопинг</a></div> -->
  <div class="Order-footer"><a class="btn btn_primary btn_lg" href="{% url 'shop:order_create' %}">Оформить заказ</a></div>

      {% else %}
        <p>Ваша корзина сейчас пуста</p>
          <a href="{% url 'shop:catalog' %}" class="btn">Вернуться в магазин</a>
      {% endif %}

      </div>
    </div>
    </div>
{% endblock middle %}