online_store/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('add_in_cat/<int:product_id>', views.cart_add_in_catalog, name='cart_add_in_catalog'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('cart_clear', views.cart_clear, name='cart_clear'),
]

online_store/online_store/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import BaseView
from django.conf import settings
from django.conf.urls.static import static
from shop.api import OrderAPIUpdate

urlpatterns = [
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('catalog/', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/order/<int:pk>/', OrderAPIUpdate.as_view(), name='order'),
    path('api/v1/order/auth/', include('rest_framework.urls')),
    path('', BaseView.as_view(), name='base'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_store/shop/urls.py
from django.urls import path
from django.views.decorators.http import require_POST

from . import views

app_name = 'shop'

urlpatterns = [
    path('<slug:cat_slug>', views.ProductCategory.as_view(), name='category'),
    path('', views.ProductListView.as_view(), name='catalog'),
    path('product/<int:pk>', views.ProductDetailView.as_view(), name='product'),
    path('product/<int:pk>/review', require_POST(views.AddReviews.as_view()), name='review'),
    path('order/create', views.OrderCreateView.as_view(), name='order_create'),
    path('order/payment/<int:pk>/', views.payment, name='order_pay'),
    path('order/progresspay', views.progress_pay, name='progress_pay'),
    path('order/history', views.OrderHistoryView.as_view(), name='order_history'),
    path('order/detail/<int:pk>/', views.OrderDetail.as_view(), name='order_detail'),
]

online_store/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path
from .views import UserLoginView,\
    UserLogoutView, \
    UserRegisterView, \
    UserSetPassword, \
    UserSetPasswordDone, \
    ProfileView, \
    ProfileUpdate


app_name = 'users'

urlpatterns = [
    path('account/<int:pk>', ProfileView.as_view(), name='account'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('set_password/', UserSetPassword.as_view(), name='set_password'),
    path('set_password/done', UserSetPasswordDone.as_view(), name='set_password_done'),
    path('profile/<int:pk>', ProfileUpdate.as_view(), name='profile_update'),
]

online_store/shop/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    slug = models.CharField(max_length=100)
    parent = models.ForeignKey('self', related_name='children', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.name!r}"


class Product(models.Model):
    class Meta:
        ordering = ["name", "price"]
        verbose_name_plural = ('Товары')
        verbose_name = ('Товар')

    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(null=False, blank=True, verbose_name='Описание')
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    # reviews =
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name!r} {self.price!r}"


class Reviews(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=500, verbose_name='Текст отзыва', help_text='Тут Ваш отзыв')
    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания', blank=True)

    class Meta:
        verbose_name_plural = ('Отзывы')
        verbose_name = ('Отзыв')

    def __str__(self):
        return f'{self.user} - {self.product}'

    def view_reviews(self):
        return self.text if len(self.text) < 15 else (self.text[:15] + '...')


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Покупатель")
    email = models.EmailField(verbose_name='E-mail заказчика')
    fio = models.CharField(max_length=60, verbose_name='ФИО заказчика')
    phone = models.CharField(max_length=18, verbose_name='Телефон заказчика')
    DELIVERY_CHOICE = (
        ('1', 'Обычная доставка'),
        ('2', 'Экспресс доставка'),
    )
    delivery_type = models.CharField(max_length=30, choices=DELIVERY_CHOICE, default='1', verbose_name='Способ доставки')
    city = models.CharField(max_length=30, verbose_name='Город')
    address = models.CharField(max_length=100, verbose_name='Адрес')
    PAYMENT_CHOICE = (
        ('1', 'Картой онлайн'),
        ('2', 'Онлайн со случайного чужого счёта')
    )
    payment_method = models.CharField(max_length=50, choices=PAYMENT_CHOICE, default='1', verbose_name='Способ оплаты')

    # order_item = models.ManyToManyField(OrderItem, blank=True, related_name='order')
    # total_price = models.PositiveIntegerField(default=0, verbose_name="Итоговая цена")
    status = models.BooleanField(default=False, verbose_name='Оплачен')
    created = models.DateTimeField(auto_now_add=True)
    error_text = models.CharField(max_length=100, blank=True, verbose_name='Ошибка')

    # добавить поля стоимости для обычной доставки и для экспресс, чтобы можно было менять в админке.
    # или лучше добавить новую модель с константами и записать туда цены на доставки и в теории можно будет еще что-то
    def __str__(self):
        return "Заказ ({})".format(self.id)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def get_total_cost(self):
        if self.delivery_type == '1':
            if sum(item.get_cost() for item in self.items.all()) >= 2000:
                return sum(item.get_cost() for item in self.items.all())
            else:
                return sum(item.get_cost() for item in self.items.all()) + 200
        else:
            return sum(item.get_cost() for item in self.items.all()) + 500

    def get_delivery_type_name(self):
        if self.delivery_type == '1':
            return 'Обычная доставка'
        else:
            return 'Экспресс доставка'

    def get_payment_method_name(self):
        if self.delivery_type == '1':
            return 'Картой онлайн'
        else:
            return 'Онлайн со случайного чужого счёта'

    def get_status(self):
        if self.status:
            return 'Оплачен'
        else:
            return 'Не оплачен'


class OrderItem(models.Model):
    product = models.ForeignKey(Product, related_name='order_item', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    price = models.DecimalField(max_digits=8, decimal_places=2)
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)

    def __str__(self):
        return "Объект: {} (заказ)".format(self.product.name)

    class Meta:
        verbose_name = 'Объект заказа'
        verbose_name_plural = 'Объекты заказа'

    def get_cost(self):
        return self.price * self.quantity

online_store/shop/forms.py
from django import forms
from .models import Reviews, Order
from django.forms import Textarea

DELIVERY_CHOICE = (
        ('1', 'Обычная доставка'),
        ('2', 'Экспресс доставка'),
    )

PAYMENT_CHOICE = (
        ('1', 'Картой онлайн'),
        ('2', 'Онлайн со случайного чужого счёта')
    )


class ReviewsForm(forms.ModelForm):

    class Meta:
        model = Reviews
        fields = ('text',)
        exclude = ('user',)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.fields['text'].widget = Textarea(attrs={'class': "form-textarea",
                                                     'name': 'review',
                                                     'id': 'review',
                                                     'placeholder': 'Review'
                                                     })


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ('email', 'fio', 'phone', 'delivery_type', 'city', 'address', 'payment_method',)

    def __init__(self,  **kwargs):
        super().__init__(**kwargs)

        self.fields['email'].widget = forms.EmailInput(attrs={'class': 'form-input'})
        self.fields['fio'].widget = forms.TextInput(attrs={'class': 'form-input'})
        self.fields['phone'].widget = forms.TextInput(attrs={'class': 'form-input'})

        self.fields['delivery_type'].widget = forms.RadioSelect(choices=DELIVERY_CHOICE)
        self.fields['payment_method'].widget = forms.RadioSelect(choices=PAYMENT_CHOICE)

        self.fields['city'].widget = forms.TextInput(attrs={'class': 'form-input'})
        self.fields['address'].widget = forms.TextInput(attrs={'class': 'form-input'})


class PayForm(forms.Form):
    card_num = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-input Payment-bill form-input_error',
    'id': 'numero1',
    'placeholder': '9999 9999',
    'data-mask': '9999 9999',
    'data-validate': 'require pay'
    }))

online_store/shop/views.py
from time import sleep

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import FormMixin, FormView
from cart.forms import CartAddProductForm
from cart.cart import Cart
from .models import Product, Reviews, Category, Order, OrderItem
from django.views.generic import DetailView, CreateView, ListView
from .forms import ReviewsForm, OrderForm, PayForm
from .filters import ProductFilter
from shop.api import OrderAPIUpdate
import requests
from rest_framework.authtoken.models import Token
from django.contrib import messages
from online_store.config import URL_API


# добавление отзыва и перенаправление обратно на страницу продукта
class AddReviews(FormView):
    model = Reviews
    template_name = 'shop/product.html'
    form_class = ReviewsForm
    # success_url = reverse_lazy('shop:product', kwargs=pk)

    def form_valid(self, form):
        print(self.kwargs)
        form_valid = super().form_valid(form)
        obj = form.save(commit=False)
        obj.user = User.objects.get(id=self.request.user.id)
        obj.product = Product.objects.get(id=self.kwargs['pk'])
        obj.save()
        return form_valid

    def get_success_url(self):
        return reverse_lazy('shop:product', kwargs={'pk': self.kwargs['pk']})


class ProductDetailView(DetailView):
    model = Product
    template_name = 'shop/product.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['review_form'] = ReviewsForm()
        context['cart_form'] = CartAddProductForm()

        return context


class ProductListView(ListView):
    model = Product
    template_name = 'shop/catalog.html'
    paginate_by = 4
    context_object_name = 'products'

    def get_ordering(self):
        ordering = self.request.GET.get('sorting')

        print(ordering)
        return ordering

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = ProductFilter(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_form'] = self.filterset.form
        # if self.ordering:
        #     context['ordering'] = self.ordering
        #     print(self.ordering)
        # print(context)
        # category = Category.objects.filter()

        return context
    # есть проблема (малая) сброс страниц и сортировки при смене фильтра,
    # но фильтр не сбрасывается при сортировке и смене страниц


class ProductCategory(ListView):
    model = Product
    template_name = 'shop/catalog.html'
    paginate_by = 4
    context_object_name = 'products'

    def get_ordering(self):
        ordering = self.request.GET.get('sorting')
        print(ordering)
        return ordering

    def get_queryset(self):
        order = self.get_ordering()
        if order:
            queryset = Product.objects.filter(category__slug=self.kwargs['cat_slug']).order_by(order)
        else:
            queryset = Product.objects.filter(category__slug=self.kwargs['cat_slug']).order_by('name')
        # Product.objects.filter(name__startswith='')
        self.filterset = ProductFilter(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_form'] = self.filterset.form
        print(self.kwargs)
        # category = Category.objects.filter()

        return context


class OrderCreateView(FormView):
    model = Order
    template_name = 'shop/order.html'
    form_class = OrderForm
    success_url = reverse_lazy('base')

    def get_context_data(self, **kwargs):
        context = super(OrderCreateView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_authenticated:
            context['order_form'] = OrderForm(initial={'fio': user.profile.fio,
                                                             'phone': user.profile.phone,
                                                             'email': user.email})
            print('Авторизован')
        else:
            context['order_form'] = OrderForm()
            print('не авторизован')
        return context

    def form_valid(self, form):
        cart = Cart(self.request)
        order = form.save(commit=False)
        order.user = self.request.user
        order.save()
        print('заказ', order)
        print('корзина', cart)
        for item in cart:
            OrderItem.objects.create(order=order,
                                     product=item['product'],
                                     price=item['price'],
                                     quantity=item['quantity'])
            print('создан объект заказа')
        cart.clear()
        return HttpResponseRedirect(reverse_lazy('shop:order_pay', kwargs={'pk': order.id }))


@login_required
def payment(request, pk):

    if request.method == 'GET':
        form = PayForm()
        order = Order.objects.get(id=pk)
        user = order.user
        print(user)
        print(request.user)
        if user != request.user:
            return HttpResponse('Это не Ваш заказ') # как вариант можно перенаправить на свои заказы

    if request.method == 'POST':
        form = PayForm(request.POST)
        order = Order.objects.get(id=pk)
        user = order.user
        print(user)
        print(request.user)
        if user == request.user:
            if form.is_valid():
                card_num = form.cleaned_data.get('card_num')
                s = requests.Session()
                Token.objects.get_or_create(user=request.user)
                token = Token.objects.get(user=request.user)

                s.headers = {'Authorization': 'Token ' + token.key}
                print(s.headers)
                url = URL_API.format(str(pk))

                r = s.post(url, json={"card_num": card_num})
                print('++++++++++++++++++++++++++++++++++++++post', r.status_code)
                print(r.text)

            return HttpResponseRedirect(reverse_lazy('shop:progress_pay'))
        else:
            return HttpResponse('Это не Ваш заказ') # как вариант можно перенаправить на свои заказы

    context = {
        'pay_form': PayForm()
    }
    return render(request, 'shop/paymentsomeone.html', context)


def progress_pay(request):

    if request.method == 'GET':
        # return HttpResponseRedirect(reverse_lazy('users:account', kwargs={'pk': request.user.id}))
        return render(request, 'shop/progressPayment.html')
    return render(request, 'shop/progressPayment.html')


class OrderHistoryView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'shop/historyorder.html'
    paginate_by = 3
    context_object_name = 'orders'

    def get_queryset(self):
        queryset = Order.objects.filter(user=self.request.user).order_by('-created')

        return queryset


class OrderDetail(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'shop/oneorder.html'
    context_object_name = 'order'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order_item'] = OrderItem.objects.filter(order=self.object)
        return context

online_store/templates/shop/paymentsomeone.html
{% extends 'index.html' %}
{% block middle %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Оплата
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{% url 'base' %}">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Оплата</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        <form class="form Payment" action="#" method="post">
            {% csrf_token %}
          <div class="Payment-card">
            <div class="form-group">
              <label class="form-label">{{ pay_form.card_num.label }}
              </label>
                {{ pay_form.card_num }}
                {{ pay_form.card_num.error }}
              </div>
            <div class="form-group"><a class="btn btn_success Payment-generate" href="#">Сгенирировать случайный счет</a>
            </div>
          </div>
          <div class="Payment-pay">
              <button class="btn btn_success" type="submit">Оплатить
                      </button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock middle %}

online_store/templates/shop/product.html
{% extends 'index.html' %}
{% load static %}

{% block middle %}

  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Megano Product
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{% url 'base' %}">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Product</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        <div class="Product">
          <div class="ProductCard">
            <div class="ProductCard-look">
              <div class="ProductCard-photo">
                <img src="{% static 'assets/img/content/home/bigGoods.png' %}" alt="bigGoods.png"/>
              </div>
              <div class="ProductCard-picts"><a class="ProductCard-pict ProductCard-pict_ACTIVE" href="{% static 'assets/img/content/home/bigGoods.png' %}">
                  <img src="{% static 'assets/img/content/home/bigGoods.png' %}" alt="bigGoods.png"/></a>
                  <a class="ProductCard-pict" href="{% static 'assets/img/content/home/slider.png' %}">
                      <img src="{% static 'assets/img/content/home/slider.png' %}" alt="slider.png"/></a>
                  <a class="ProductCard-pict" href="{% static 'assets/img/content/home/videoca.png' %}">
                      <img src="{% static 'assets/img/content/home/videoca.png' %}" alt="videoca.png"/></a>
              </div>
            </div>
            <div class="ProductCard-desc">
              <div class="ProductCard-header">
                <h2 class="ProductCard-title">{{ product.name }}
                </h2>
                <div class="ProductCard-info">
                  <div class="ProductCard-cost">
                    <div class="ProductCard-price">{{ product.price }}
                    </div>
                  </div>
                </div>
              </div>
              <div class="ProductCard-text">
                 {{ product.description }}
              </div>

            <form action="{% url 'cart:cart_add' product.id %}" method="post">


              <div class="ProductCard-cart">
                <div class="ProductCard-cartElement ProductCard-cartElement_amount">
                  <div class="Amount Amount_product">

                    {% csrf_token %}
                    <!--<input type="submit" value="В корзину"> -->

                    <button class="Amount-remove" type="button">
                    </button>
                      {{ cart_form.quantity }}
                    <!--<input class="Amount-input form-input" name="amount" type="text" value="1"/> -->
                    <button class="Amount-add" type="button">
                    </button>

                  </div>
                </div>
                <div class="ProductCard-cartElement">

                    <button class="btn btn_primary" type="submit">
                    <a class="btn btn_primary" type="submit">
                    <img class="btn-icon" src="{% static 'assets/img/icons/card/cart_white.svg' %}" alt="cart_white.svg"/>
                    <span class="btn-content" type="submit">Add To Cart</span></a></button>

                <!--
                    <a class="btn btn_primary" href="#">
                    <img class="btn-icon" src="{% static 'assets/img/icons/card/cart_white.svg' %}" alt="cart_white.svg"/>
                    <span class="btn-content" type="submit">Add To Cart</span></a> -->
                </div>
              </div>
                </form>

              <div class="ProductCard-footer">
                <div class="ProductCard-tags">
                  <strong class="ProductCard-tagsTitle">Tags:
                  </strong> {{ product.category }}<!--<a href="#">Accesories</a>,<a href="#">Creative</a>,<a href="#">Design</a>,<a href="#">Gaming</a>-->
                </div>
              </div>
            </div>
          </div>
          <div class="Tabs Tabs_default">
            <div class="Tabs-links"><a class="Tabs-link_ACTIVE Tabs-link" href="#description"><span>Описание</span></a>
              <!-- <a class="Tabs-link" href="#addit"><span>AdditionaL Info</span></a> -->
                <a class="Tabs-link" href="#reviews"><span>Reviews ({{ product.reviews.count }})</span></a>
            </div>
            <div class="Tabs-wrap">
              <div class="Tabs-block" id="description">
                <h2>{{  product.name }}
                </h2>
                <p>{{ product.description }}
                    <strong>В наличии: {{ product.quantity }} шт.</strong>
                </p><img class="pict pict_right" src="{% static 'assets/img/content/home/bigGoods.png' %}" alt="bigGoods.png"/>

                <!--<div class="clearfix">
                </div>
                <div class="table">
                  <table>
                    <tr>
                      <th>Характеристика
                      </th>
                      <th>Значение
                      </th>
                    </tr>
                    <tr>
                      <td>ываыв
                      </td>
                      <td>llslssl
                      </td>
                    </tr>
                  </table>
                </div> -->
              </div>
              <div class="Tabs-block" id="sellers">
                <div class="Categories Categories_product">
                </div>
              </div>
             <div class="Tabs-block" id="addit">
                <div class="Product-props">
                  <div class="Product-prop">
                    <strong>Lorem
                    </strong><span> Pfizer</span>
                  </div>
                  <div class="Product-prop">
                    <strong>ipsum
                    </strong><span> Lorem ipsum dolor sit</span>
                  </div>
                  <div class="Product-prop">
                    <strong>dolor sit
                    </strong><span> 5 ans</span>
                  </div>
                  <div class="Product-prop">
                    <strong>psum dolo
                    </strong><span> 2–3 jours</span>
                  </div>
                </div>
              </div>

              <div class="Tabs-block" id="reviews">
                <header class="Section-header">
                  <h3 class="Section-title">{{ product.reviews.count }} Reviews
                  </h3>
                </header>

                {% for rev in product.reviews.all %}
                <div class="Comments">
                  <div class="Comment">
                    <div class="Comment-column Comment-column_pict">
                      <div class="Comment-avatar">
                      </div>
                    </div>
                    <div class="Comment-column">
                      <header class="Comment-header">
                        <div>
                          <strong class="Comment-title">{{ rev.user }}
                          </strong><span class="Comment-date">{{ rev.created }}</span>
                        </div>
                      </header>
                      <div class="Comment-content"> {{ rev.text }}
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
                <header class="Section-header Section-header_product">
                  <h3 class="Section-title">Add Review
                  </h3>
                </header>
                <div class="Tabs-addComment">
                    {% if request.user.is_authenticated %}
                  <form class="form" action="{% url 'shop:review' pk=product.pk %}" method="post">
                      {% csrf_token %}
                    <div class="form-group">
                        {{ review_form.text }}
                      <!--<textarea class="form-textarea" name="review" id="review" placeholder="Review" ></textarea>-->

                    </div>

                    <div class="form-group">
                      <button class="btn btn_muted" type="submit">Submit Review
                      </button>
                    </div>
                  </form>
                    {% else %}

                    <strong class="Comment-title">Для добавления отзыва нужно авторизоваться
                        <a href="{% url 'users:login' %}">Войти</a>
                        <a href="{% url 'users:register' %}">Регистрация</a>
                    </strong>

                    {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>

{% endblock middle %}

online_store/templates/shop/progressPayment.html
{% extends 'index.html' %}
{% block middle %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Ожидание оплаты
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{% url 'base' %}">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Ожидание оплаты</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        <div class="ProgressPayment">
          <div class="ProgressPayment-title">Ждем подтверждения оплаты платежной системой
          </div>
          <div class="ProgressPayment-icon">
            <div class="cssload-thecube">
              <div class="cssload-cube cssload-c1"></div>
              <div class="cssload-cube cssload-c2"></div>
              <div class="cssload-cube cssload-c4"></div>
              <div class="cssload-cube cssload-c3"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock middle %}