online_store/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('add_in_cat/<int:product_id>', views.cart_add_in_catalog, name='cart_add_in_catalog'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('cart_clear', views.cart_clear, name='cart_clear'),
]

online_store/online_store/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import BaseView
from django.conf import settings
from django.conf.urls.static import static
from shop.api import OrderAPIUpdate

urlpatterns = [
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('catalog/', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/order/<int:pk>/', OrderAPIUpdate.as_view(), name='order'),
    path('api/v1/order/auth/', include('rest_framework.urls')),
    path('', BaseView.as_view(), name='base'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_store/shop/urls.py
from django.urls import path
from django.views.decorators.http import require_POST

from . import views

app_name = 'shop'

urlpatterns = [
    path('<slug:cat_slug>', views.ProductCategory.as_view(), name='category'),
    path('', views.ProductListView.as_view(), name='catalog'),
    path('product/<int:pk>', views.ProductDetailView.as_view(), name='product'),
    path('product/<int:pk>/review', require_POST(views.AddReviews.as_view()), name='review'),
    path('order/create', views.OrderCreateView.as_view(), name='order_create'),
    path('order/payment/<int:pk>/', views.payment, name='order_pay'),
    path('order/progresspay', views.progress_pay, name='progress_pay'),
    path('order/history', views.OrderHistoryView.as_view(), name='order_history'),
    path('order/detail/<int:pk>/', views.OrderDetail.as_view(), name='order_detail'),
]

online_store/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path
from .views import UserLoginView,\
    UserLogoutView, \
    UserRegisterView, \
    UserSetPassword, \
    UserSetPasswordDone, \
    ProfileView, \
    ProfileUpdate


app_name = 'users'

urlpatterns = [
    path('account/<int:pk>', ProfileView.as_view(), name='account'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('set_password/', UserSetPassword.as_view(), name='set_password'),
    path('set_password/done', UserSetPasswordDone.as_view(), name='set_password_done'),
    path('profile/<int:pk>', ProfileUpdate.as_view(), name='profile_update'),
]

online_store/users/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist

User._meta.get_field('email')._unique = True


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, null=True, max_length=10, verbose_name='Телефон',
                             help_text='Введите без +7')
    fio = models.CharField(blank=True, null=True, max_length=60, verbose_name='ФИО')
    p_img = models.ImageField(default='user_avatar/cat_1.jpg',
                              upload_to='user_avatar/',
                              null=True,
                              blank=True
                              )

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def __str__(self):
        return self.user.username

    # @property
    # def get_photo_url(self):
    #     if self.p_img and hasattr(self.p_img, 'url'):
    #         return self.p_img.url
    #     else:
    #         return "/static/images/user.jpg"


@receiver(post_save, sender=User)
def save_or_create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        my_group = Group.objects.get(name='Buyer')
        my_group.user_set.add(instance)
    else:
        try:
            instance.profile.save()
        except ObjectDoesNotExist:
            Profile.objects.create(user=instance)
            my_group = Group.objects.get(name='Buyer')
            my_group.user_set.add(instance)

online_store/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class RegisterForm(UserCreationForm):
    # first_name = forms.CharField(max_length=30, required=False, help_text='Имя')
    # last_name = forms.CharField(max_length=30, required=False, help_text='Фамилия')
    email = forms.EmailField(label='E-mail', widget=forms.EmailInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


class ProfileUpdateForm(forms.ModelForm):
    email = forms.EmailField(required=False, label='E-mail', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    phone = forms.CharField(required=False, max_length=10, label='Телефон',
                            widget=forms.TextInput(attrs={'class': 'form-input'}))
    fio = forms.CharField(required=False, max_length=60, label='ФИО',
                          widget=forms.TextInput(attrs={'class': 'form-input'}))
    p_img = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'Profile-file form-input'}))

    class Meta:
        model = Profile
        fields = ('phone', 'fio', 'p_img')
# <input class="Profile-file form-input" id="avatar" name="avatar" type="file" data-validate="onlyImgAvatar">

online_store/users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DetailView
from .forms import RegisterForm, ProfileUpdateForm
from .models import Profile
from shop.models import Order


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    success_url = reverse_lazy('/')

    # def get_success_url(self):
    #     print('путь', self.request.META.get('HTTP_REFERER'))
    #     return self.request.META.get('HTTP_REFERER')


class UserLogoutView(LogoutView):
    template_name = 'users/logout.html'
    success_url = reverse_lazy('/')


class UserRegisterView(CreateView):
    model = User
    template_name = 'users/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('base')

    def form_valid(self, form):
        form_valid = super().form_valid(form)
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        login(self.request, user)
        return form_valid


class UserSetPassword(PasswordChangeView):
    template_name = 'users/set_password.html'
    success_url = reverse_lazy('users:set_password_done')


class UserSetPasswordDone(PasswordChangeDoneView):
    template_name = 'users/set_password_done.html'
    success_url = reverse_lazy('base')


class ProfileView(LoginRequiredMixin, DetailView):
    template_name = 'users/account.html'
    model = User
    context_object_name = "user"
    # @method_decorator(login_required)
    # def dispatch(self, request, *args, **kwargs):
    #     super().dispatch(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['last_order'] = Order.objects.filter(user=self.object).order_by('-created')[0]
        return context


class ProfileUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'users/profile.html'
    model = Profile
    form_class = ProfileUpdateForm


    # @method_decorator(login_required)
    # def dispatch(self, request, *args, **kwargs):
    #     super().dispatch(request, *args, **kwargs)
    # def get_success_url(self):
    #     return reverse_lazy('users:account', kwargs={'pk': self.get_object().id})



    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # if user.is_authenticated:
        #     print('Авторизован')
        # else:
        #     print('не авторизован')
        context['profile_form'] = ProfileUpdateForm(instance=self.request.user.profile,
                                                    initial={'fio': user.profile.fio,
                                                             'phone': user.profile.phone,
                                                             'email': user.email,
                                                             'p_img': user.profile.p_img})
        return context

    def form_valid(self, form):
        fio = form.cleaned_data['fio']
        phone = form.cleaned_data['phone']
        email = form.cleaned_data['email']
        p_img = form.cleaned_data['p_img']
        profile = form.save(commit=False)
        user = profile.user
        user.email = email
        user.save()
        profile.save()
        return HttpResponseRedirect(reverse_lazy('users:profile_update', kwargs={'pk': self.get_object().id}))

online_store/templates/users/account.html
{% extends 'index.html' %}
{% load static %}

{% block middle %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Личный кабинет
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="../index.html">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Личный кабинет</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">Навигация
              </strong>
            </header>
            <div class="Section-columnContent">
              <div class="NavigateProfile">
                <ul class="menu menu_vt">
                  <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url 'users:account' pk=user.pk %}">Личный кабинет</a>
                  </li>
                  <li class="menu-item"><a class="menu-link" href="{% url 'users:profile_update' pk=user.pk %}">Профиль</a>
                  </li>
                  <li class="menu-item"><a class="menu-link" href="{% url 'shop:order_history' %}">История заказов</a>
                  </li>
                 <!-- <li class="menu-item"><a class="menu-link" href="historyview.html">История просмотра</a>
                  </li> -->
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <div class="Account">
            <div class="Account-group">
              <div class="Account-column">
                  {% if user.profile.p_img %}
                    <div class="Account-avatar"><img src="{{ user.profile.p_img.url }}" alt="card.jpg"/>
                    </div>
                  {% else %}
                     <div class="Account-avatar"><img src="{% static 'assets/img/content/home/slider.png' %}" alt="card.jpg"/>
                    </div>
                  {% endif %}
              </div>
              <div class="Account-column">
                <div class="Account-name">ФИО: {{ user.profile.fio }} Никнейм: {{ user.username }}
                </div><a class="Account-editLink" href="{% url 'users:profile_update' pk=user.pk %}">Редактировать профиль</a>
              </div>
            </div>
            <div class="Account-group">
              <div class="Account-column Account-column_full">
                <div class="Order Order_anons">
                  <div class="Order-personal">
                    <div class="row">

                      <div class="row-block"><a class="Order-title" href="{% url 'shop:order_detail' pk=last_order.pk %}">
                          Заказ <span class="Order-numberOrder">№{{ last_order.id }}</span>
                          от <span class="Order-dateOrder">{{ last_order.created }}</span></a>
                        <div class="Account-editLink"><a href="{% url 'shop:order_history' %}">История заказов</a>
                        </div>
                      </div>
                      <div class="row-block">
                        <div class="Order-info Order-info_delivery">
                          <div class="Order-infoType">Тип доставки:
                          </div>
                          <div class="Order-infoContent">{{ last_order.get_delivery_type_name }}
                          </div>
                        </div>
                        <div class="Order-info Order-info_pay">
                          <div class="Order-infoType">Оплата:
                          </div>
                          <div class="Order-infoContent">{{ last_order.get_payment_method_name }}
                          </div>
                        </div>
                        <div class="Order-info">
                          <div class="Order-infoType">Общая стоимость:
                          </div>
                          <div class="Order-infoContent">{{ last_order.get_total_cost }}
                          </div>
                        </div>
                        <div class="Order-info Order-info_status">
                          <div class="Order-infoType">Статус:
                          </div>
                          <div class="Order-infoContent">{{ last_order.get_status }}</div>
                        </div>
                            {% if last_order.error_text %}
                          <div class="Order-info Order-info_error">
                            <div class="Order-infoType">
                          </div>
                          <div class="Order-infoContent">{{ last_order.error_text }}</div>
                        </div>
                          {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock middle %}

online_store/templates/users/login.html
{% extends 'index.html' %}

{% block middle %}
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <div class="Section-content">
            <h2>Страница входа</h2>
            <form method="post">
                {% csrf_token %}

                <div class="row-block">
                          <div class="form-group">
                            <label class="form-label" for="username">{{ form.username.label_tag }}
                            </label>
                              {{ form.username }}

                          </div>
                          <div class="form-group">
                            <label class="form-label" for="pass">{{ form.password.label_tag }}
                            </label>

                              {{ form.password }}

                          </div>
                    <div class="Profile-btn">
                      <button class="btn btn_success" type="submit">Войти
                      </button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
{% endblock middle %}

online_store/templates/users/logout.html
{% extends 'index.html' %}

{% block middle %}
    <div class="Middle">
    Вы успешно выли из под вашей учетной записи!
    </div>
{% endblock middle %}

online_store/templates/users/profile.html
{% extends 'index.html' %}
{% load static %}

{% block middle %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Профиль
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{% url 'base' %}">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Профиль</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">Навигация
              </strong>
            </header>
            <div class="Section-columnContent">
              <div class="NavigateProfile">
                <ul class="menu menu_vt">
                  <li class="menu-item"><a class="menu-link" href="{% url 'users:account' pk=user.pk %}">Личный кабинет</a>
                  </li>
                  <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url 'users:profile_update' pk=user.pk %}">Профиль</a>
                  </li>
                  <li class="menu-item"><a class="menu-link" href="{% url 'shop:order_history' %}">История заказов</a>
                  </li>

                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <div class="Profile">

            <form class="form Profile-form" action="#" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <!--{% for field in form %}
                    <label class="label-class">{{ field.label }}</label>
                    {{ field }}
                {% endfor %}
                -->

              <div class="row">
                <div class="row-block">
                  <div class="form-group">
                    <label class="form-label" for="avatar">Аватар профиля<!--{{ profile_form.p_img.label }}-->

                    </label>

                    <div class="Profile-avatar">
                        {% if user.profile.p_img %}
                            <div class="Profile-img">
                                <img src="{{ user.profile.p_img.url }}" alt="#.png"/>
                            </div>
                        {% else %}
                            <div class="Profile-img"><img src="#" alt="#.png"/>
                            </div>
                            <label class="Profile-fileLabel" for="avatar">Выберите аватар
                            </label>
                        {% endif %}


                        {{ profile_form.p_img }}
                        {{ profile_form.p_img.errors }}
                      <!--<input class="Profile-file form-input" id="avatar" name="avatar" type="file" data-validate="onlyImgAvatar"/> -->
                    </div>
                  </div>


                </div>

                <div class="row-block">
                    <div class="form-group">
                    <label class="form-label" for="name">{{ profile_form.fio.label }}</label>
                      {{ profile_form.fio }}
                      {{ profile_form.fio.errors }}
                  </div>
                  <div class="form-group">
                    <label class="form-label" for="phone">{{ profile_form.phone.label }}
                    </label>
                    {{ profile_form.phone }}
                    {{ profile_form.phone.errors }}
                  </div>

                  <div class="form-group">
                    <label class="form-label" for="mail">{{ profile_form.email.label }}
                    </label>
                    {{ profile_form.email }}
                    {{ profile_form.email.errors }}
                  </div>

                  <!--<div class="form-group">
                    <label class="form-label" for="password">Пароль
                    </label>
                    <input class="form-input" id="password" name="password" type="password" placeholder="Тут можно изменить пароль"/>
                  </div>

                  <div class="form-group">
                    <label class="form-label" for="passwordReply">Подтверждение пароля
                    </label>
                    <input class="form-input" id="passwordReply" name="passwordReply" type="password" placeholder="Введите пароль повторно"/>
                  </div> -->

                  <div class="form-group">
                    <div class="Profile-btn">
                      <button class="btn btn_success" type="submit">Сохранить
                      </button>
                    <!--</div>
                    <div class="Profile-success">Профиль успешно сохранен
                    </div>-->
                  </div>
                  </div>
                </div>
              </div>
            </form>

          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock middle %}

online_store/templates/users/register.html
{% extends 'index.html' %}

{% block middle %}
    <div class="Middle">
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <div class="Section-content">
            <h2>Регистрация</h2>
                {% if forms.errors %}
                    Ошибка {{ forms.errors }}
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    <div class="row-block">
                          <div class="form-group">
                            <label class="form-label" for="username">{{ form.username.label_tag }}
                            </label>
                              {{ form.username }}

                          </div>
                          <div class="form-group">
                            <label class="form-label" for="first_name">{{ form.email.label }}
                            </label>

                              {{ form.email }}

                          </div>
                       <!-- </div>
                          <div class="form-group">
                            <label class="form-label" for="first_name">{{ form.first_name.help_text }}
                            </label>

                              {{ form.first_name }}

                          </div>
                        <div class="form-group">
                            <label class="form-label" for="last_name">{{ form.last_name.help_text }}
                            </label>

                              {{ form.last_name }}

                          </div>-->

                         <div class="form-group">
                            <label class="form-label" for="pass1">{{ form.password1.label_tag }}
                            </label>

                              {{ form.password1 }}

                          </div>
                         <div class="form-group">
                            <label class="form-label" for="pass2">{{ form.password2.label_tag }}
                            </label>

                              {{ form.password2 }}

                          </div>
                        <div class="Profile-btn">
                      <button class="btn btn_success" type="submit">Зарегистрироваться
                      </button>
                    </div>
                    </div>
                </form>
                </div>
            </div>
    </div>
    </div>
{% endblock middle %}

online_store/templates/users/set_password.html
{% extends 'index.html' %}

{% block middle %}
    <div class="Middle">
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <div class="Section-content">
            <h2>Страница смены пароля</h2>
                {% if forms.errors %}
                    Ошибка {{ forms.errors }}
                {% endif %}
            <form method="post">
                {% csrf_token %}

                <div class="row-block">
                          <div class="form-group">

                              {{ form.as_p }}

                          </div>

                    <div class="Profile-btn">
                      <button class="btn btn_success" type="submit">Изменить
                      </button>
                    </div>
                    </div>
            </form>
            </div>
        </div>
    </div>
    </div>
{% endblock middle %}

online_store/templates/users/set_password_done.html
{% extends 'index.html' %}

{% block middle %}
    <div class="Middle">
    Вы успешно изменили пароль
    </div>
{% endblock middle %}